CREATE USER thony IDENTIFIED BY 123456;
CREATE USER javi IDENTIFIED BY 123456;
CREATE USER tato IDENTIFIED BY 123456;
CREATE USER juan IDENTIFIED BY 123456;
CREATE USER pepe IDENTIFIED BY 123456;

--ASIGNACIONES DE ROL

GRANT system_admin to thony;
GRANT business_admin to javi;
GRANT developer to tato;
GRANT reports_manager to juan;
GRANT client to pepe;


