--business_admin

GRANT CREATE SESSION TO business_admin;

GRANT SELECT ON AEROLINEA TO business_admin;
GRANT SELECT ON AVION TO business_admin;
GRANT SELECT ON TIPO_AVION TO business_admin;
GRANT SELECT ON ASIENTO TO business_admin;
GRANT SELECT ON CLASE_AEROLINEA TO business_admin;
GRANT SELECT ON CLASE TO business_admin;
GRANT SELECT ON TRAYECTO TO business_admin;
GRANT SELECT ON VUELO TO business_admin;
GRANT SELECT ON AEROPUERTO TO business_admin;
GRANT SELECT ON ASEGURADORA TO business_admin;
GRANT SELECT ON SEGURO TO business_admin;
GRANT SELECT ON LUGAR TO business_admin;
GRANT SELECT ON CLIENTE TO business_admin;
GRANT SELECT ON USUARIO TO business_admin;
GRANT SELECT ON PAGO TO business_admin;
GRANT SELECT ON HISTORICO_MILLA TO business_admin;
GRANT SELECT ON TARJETA TO business_admin;
GRANT SELECT ON RESERVACION TO business_admin;
GRANT SELECT ON VEHICULO TO business_admin;
GRANT SELECT ON PROVEEDOR_VEHICULO TO business_admin;
GRANT SELECT ON SUCURSAL TO business_admin;
GRANT SELECT ON HABITACION TO business_admin;
GRANT SELECT ON MODELO_VEHICULO TO business_admin;
GRANT SELECT ON ALOJAMIENTO TO business_admin;
GRANT SELECT ON LUG_ALOJ TO business_admin;

GRANT INSERT,UPDATE,DELETE ON AVION TO business_admin;
GRANT INSERT,UPDATE,DELETE ON TIPO_AVION TO business_admin;
GRANT UPDATE ON CLASE_AEROLINEA TO business_admin;
GRANT UPDATE ON CLASE TO business_admin;
GRANT INSERT,UPDATE,DELETE ON VUELO TO business_admin;
GRANT INSERT,UPDATE,DELETE ON ASEGURADORA TO business_admin;
GRANT INSERT,UPDATE,DELETE ON CLIENTE TO business_admin;
GRANT INSERT ON PAGO TO business_admin;
GRANT INSERT,UPDATE,DELETE ON RESERVACION TO business_admin;
GRANT INSERT,UPDATE,DELETE ON VEHICULO TO business_admin;
GRANT INSERT,UPDATE,DELETE ON PROVEEDOR_VEHICULO TO business_admin;
GRANT INSERT,UPDATE ON SUCURSAL TO business_admin;
GRANT INSERT,UPDATE ON HABITACION TO business_admin;
GRANT INSERT ON MODELO_VEHICULO TO business_admin;
GRANT INSERT,UPDATE,DELETE ON ALOJAMIENTO TO business_admin;
GRANT INSERT,UPDATE,DELETE ON LUG_ALOJ TO business_admin;
