--developer

GRANT CREATE SESSION TO developer;

--CRUD

GRANT SELECT ON AEROLINEA TO developer;
GRANT SELECT ON AVION TO developer;
GRANT SELECT ON TIPO_AVION TO developer;
GRANT SELECT ON ASIENTO TO developer;
GRANT SELECT ON CLASE_AEROLINEA TO developer;
GRANT SELECT ON CLASE TO developer;
GRANT SELECT ON TRAYECTO TO developer;
GRANT SELECT ON VUELO TO developer;
GRANT SELECT ON AEROPUERTO TO developer;
GRANT SELECT ON ASEGURADORA TO developer;
GRANT SELECT ON SEGURO TO developer;
GRANT SELECT ON LUGAR TO developer;
GRANT SELECT ON CLIENTE TO developer;
GRANT SELECT ON USUARIO TO developer;
GRANT SELECT ON PAGO TO developer;
GRANT SELECT ON HISTORICO_MILLA TO developer;
GRANT SELECT ON TARJETA TO developer;
GRANT SELECT ON RESERVACION TO developer;
GRANT SELECT ON VEHICULO TO developer;
GRANT SELECT ON PROVEEDOR_VEHICULO TO developer;
GRANT SELECT ON SUCURSAL TO developer;
GRANT SELECT ON HABITACION TO developer;
GRANT SELECT ON MODELO_VEHICULO TO developer;
GRANT SELECT ON ALOJAMIENTO TO developer;
GRANT SELECT ON LUG_ALOJ TO developer;

GRANT INSERT,UPDATE,DELETE ON AEROLINEA TO developer;
GRANT INSERT,UPDATE,DELETE ON AVION TO developer;
GRANT INSERT,UPDATE,DELETE ON TIPO_AVION TO developer;
GRANT INSERT,UPDATE,DELETE ON ASIENTO TO developer;
GRANT INSERT,UPDATE,DELETE ON CLASE_AEROLINEA TO developer;
GRANT INSERT,UPDATE,DELETE ON CLASE TO developer;
GRANT INSERT,UPDATE,DELETE ON TRAYECTO TO developer;
GRANT INSERT,UPDATE,DELETE ON VUELO TO developer;
GRANT INSERT,UPDATE,DELETE ON AEROPUERTO TO developer;
GRANT INSERT,UPDATE,DELETE ON ASEGURADORA TO developer;
GRANT INSERT,UPDATE,DELETE ON SEGURO TO developer;
GRANT INSERT,UPDATE,DELETE ON LUGAR TO developer;
GRANT INSERT,UPDATE,DELETE ON CLIENTE TO developer;
GRANT INSERT,UPDATE,DELETE ON USUARIO TO developer;
GRANT INSERT,UPDATE,DELETE ON PAGO TO developer;
GRANT INSERT,UPDATE,DELETE ON HISTORICO_MILLA TO developer;
GRANT INSERT,UPDATE,DELETE ON TARJETA TO developer;
GRANT INSERT,UPDATE,DELETE ON RESERVACION TO developer;
GRANT INSERT,UPDATE,DELETE ON VEHICULO TO developer;
GRANT INSERT,UPDATE,DELETE ON PROVEEDOR_VEHICULO TO developer;
GRANT INSERT,UPDATE,DELETE ON SUCURSAL TO developer;
GRANT INSERT,UPDATE,DELETE ON HABITACION TO developer;
GRANT INSERT,UPDATE,DELETE ON MODELO_VEHICULO TO developer;
GRANT INSERT,UPDATE,DELETE ON ALOJAMIENTO TO developer;
GRANT INSERT,UPDATE,DELETE ON LUG_ALOJ TO developer;

--GENERAL

GRANT CREATE TABLE TO developer;
GRANT CREATE ROLE TO developer;
GRANT CREATE USER TO developer;
GRANT DROP USER TO developer;
GRANT CREATE PROCEDURE TO developer;
GRANT CREATE TRIGGER TO developer;
GRANT CREATE VIEW TO developer;
GRANT CREATE SEQUENCE TO developer;