--tipo VARCHAR2(50) NOT NULL CHECK( tipo = 'CALLE' OR tipo = 'CIUDAD' OR tipo = 'ESTADO' OR tipo = 'PAIS' OR tipo = 'CONTINENTE' ),

-- CONTINENTE
	INSERT INTO Lugar VALUES(1,NULL,'CONTINENTE','Norte America', NULL);
	INSERT INTO Lugar VALUES(2,NULL,'CONTINENTE','Asia',NULL);
	INSERT INTO Lugar VALUES(3,NULL,'CONTINENTE','Africa',NULL);
	INSERT INTO Lugar VALUES(4,NULL,'CONTINENTE','Europa',NULL);
	INSERT INTO Lugar VALUES(5,NULL,'CONTINENTE','Sur America',NULL);
	INSERT INTO Lugar VALUES(6,NULL,'CONTINENTE','Oceania',NULL);
	INSERT INTO Lugar VALUES(7,NULL,'CONTINENTE','Antarctica', NULL);

-- PAIS
	INSERT INTO Lugar VALUES(8,5,'PAIS','Brasil', NULL);
	INSERT INTO Lugar VALUES(9,5,'PAIS','Venezuela', NULL);
	INSERT INTO Lugar VALUES(10,5,'PAIS','Aruba', NULL);
	INSERT INTO Lugar VALUES(9,5,'PAIS','Venezuela', NULL);
	INSERT INTO Lugar VALUES(9,5,'PAIS','Venezuela', NULL);

-- ESTADO
-- CIUDAD
-- CALLE