
-- TDAs
	-- PERIODO
		CREATE OR REPLACE TYPE Periodo AS OBJECT (
			-- ! NOT NULL sin funcionar
			fecha_inicio TIMESTAMP,
			fecha_fin TIMESTAMP,
			
			STATIC FUNCTION validar_periodo( fecha_inicio TIMESTAMP, fecha_fin TIMESTAMP ) RETURN NUMBER, -- DEVUELVE 1 o 0
			MEMBER FUNCTION tiempo_promedio_trayecto( trayecto_id NUMBER ) RETURN NUMBER,
			MEMBER FUNCTION diferencia_de_tiempo RETURN NUMBER
		);

		CREATE OR REPLACE TYPE BODY Periodo AS
			STATIC FUNCTION validar_periodo( fecha_inicio TIMESTAMP, fecha_fin TIMESTAMP ) RETURN NUMBER IS
				var_temporal NUMBER;	
			BEGIN
				RETURN 1;
			END;

			MEMBER FUNCTION tiempo_promedio_trayecto( trayecto_id NUMBER ) RETURN NUMBER IS
				var_temporal NUMBER;	
			BEGIN
				RETURN 1;
			END;

			MEMBER FUNCTION diferencia_de_tiempo RETURN NUMBER IS
			BEGIN
				RETURN 1;
			END;
		END;

-- TABLAS
	CREATE TABLE Tipo_Avion (
		id                      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
		nombre                  VARCHAR2(50) NOT NULL,
		modelo                  VARCHAR2(50) NOT NULL
		/* 
		TODO: Blob
		foto
		TODO: TDA Unidad                    
		velocidad_max
		alcance_max
		altitud_max
		evergadura
		ancho_interior_cabina
		altura_interior_cabina */
	);