-- * NOTA - ORDEN CONTRARIO DE CREACION

-- CLIENTES
DROP TABLE Tarjeta;
DROP TABLE Usuario;
DROP TABLE Cliente;

-- SEGUROS
DROP TABLE Seguro;
DROP TABLE Aseguradora;

-- VEHICULOS
DROP TABLE Sucursal;
DROP TABLE Vehiculo;
DROP TABLE Proveedor_Vehiculo;
DROP TABLE Modelo_Vehiculo;

-- HABITACIONES
DROP TABLE Habitacion;
DROP TABLE Alojamiento;

-- VUELOS
DROP TABLE Vuelo;
DROP TABLE Trayecto;
DROP TABLE Aeropuerto;
DROP TABLE Lugar;

-- AVIONES
DROP TABLE Asiento;
DROP TABLE Clase_Aerolinea;
DROP TABLE Clase;
DROP TABLE Avion;
DROP TABLE Aerolinea;
DROP TABLE Tipo_Avion;