-- * NOTA - ORDEN CONTRARIO DE CREACION
DROP TABLE Proveedor_Vehiculo;
DROP TABLE Modelo_Vehiculo;

-- PARA CREAR HABITACIONES
DROP TABLE Habitacion;
DROP TABLE Alojamiento;

-- PARA CREAR VUELOS
DROP TABLE Vuelo;
DROP TABLE Trayecto;
DROP TABLE Aeropuerto;
DROP TABLE Lugar;

-- PARA CREAR AVIONES
DROP TABLE Asiento;
DROP TABLE Clase_Aerolinea;
DROP TABLE Clase;
DROP TABLE Avion;
DROP TABLE Aerolinea;
DROP TABLE Tipo_Avion;