INSERT INTO Lugar VALUES(1,NULL,'CONTINENTE','Norte America', NULL);
INSERT INTO Lugar VALUES(2,NULL,'CONTINENTE','Asia',NULL);
INSERT INTO Lugar VALUES(3,NULL,'CONTINENTE','Africa',NULL);
INSERT INTO Lugar VALUES(4,NULL,'CONTINENTE','Europa',NULL);
INSERT INTO Lugar VALUES(5,NULL,'CONTINENTE','Sur America',NULL);
INSERT INTO Lugar VALUES(6,NULL,'CONTINENTE','Oceania',NULL);
INSERT INTO Lugar VALUES(7,NULL,'CONTINENTE','Antarctica', NULL);
